title: cortex42's blog
author: cortex42
name: cortex42's blog
url: https://cortex42.github.io/
description: infosec writeups, tips and tricks

permalink: /:year/:month/:day/:title/
paginate: 10
future: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

theme: jekyll-theme-hacker

