title: cortex42's pentesting notes
author: cortex42
name: cortex42's pentesting notes
url: https://cortex42.github.io/
description: my personal collection of pentesting tips and tricks

permalink: /:year/:month/:day/:title/
paginate: 10
future: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

theme: jekyll-theme-hacker

